language: ruby

gemfile:
- Gemfile
- chef-12.5.Gemfile

sudo: required

dist: trusty

rvm:
- 2.3.1

env:
- SUITE=other
- SUITE=centos
- SUITE=ubuntu

services:
- docker

script:
- bundle exec ./.travis.sh

matrix:
  allow_failures:
  - gemfile: chef-12.5.Gemfile
  fast_finish: true
